### ISSUE TITLE
Ошибка сервера JSONDecoderError from None

### ISSUE THREAD

**Issue by protsenkovi** [SashkaShashka/Programming_technologies_lab2#3]
При аварийном отключении одного клиента и получении сообщения от другого сервер падает с ошибкой json.decoder.JSONDecodeError:
```
Waiting for connection...
Connection established with:  127.0.0.1:60676
Connection established with:  127.0.0.1:60677
Traceback (most recent call last):
  File "/Users/vlpr/tmp/odobesky_andreev/Programming_technologies_lab2/Server.py", line 59, in <module>
    answers = [f.result() for f in futures]
  File "/Users/vlpr/tmp/odobesky_andreev/Programming_technologies_lab2/Server.py", line 59, in <listcomp>
    answers = [f.result() for f in futures]
  File "/Users/vlpr/miniforge3/envs/odobesky_andreev/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/Users/vlpr/miniforge3/envs/odobesky_andreev/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/vlpr/miniforge3/envs/odobesky_andreev/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/vlpr/tmp/odobesky_andreev/Programming_technologies_lab2/Server.py", line 23, in clientThread
    answer = json.loads(clientSocket.recv(1024).decode("utf-8"))
  File "/Users/vlpr/miniforge3/envs/odobesky_andreev/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/vlpr/miniforge3/envs/odobesky_andreev/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/vlpr/miniforge3/envs/odobesky_andreev/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by SashkaShashka** [comment]
Исправлено
